import { Coffee } from './components/coffee-card'

export const coffees: Coffee[] = [
  {
    id: crypto.randomUUID(),
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    imageUrl: '/src/assets/coffees/expresso.png',
    price: 6.9,
    tags: ['Tradicional'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    imageUrl: '/src/assets/coffees/americano.png',
    price: 6.9,
    tags: ['Tradicional'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    imageUrl: '/src/assets/coffees/expresso-cremoso.png',
    price: 6.9,
    tags: ['Tradicional'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    imageUrl: '/src/assets/coffees/cafe-gelado.png',
    price: 6.9,
    tags: ['Tradicional', 'Gelado'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    imageUrl: '/src/assets/coffees/cafe-com-leite.png',
    price: 9.9,
    tags: ['Tradicional', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    imageUrl: '/src/assets/coffees/latte.png',
    price: 9.9,
    tags: ['Tradicional', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    imageUrl: '/src/assets/coffees/capuccino.png',
    price: 9.9,
    tags: ['Tradicional', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    imageUrl: '/src/assets/coffees/macchiato.png',
    price: 9.9,
    tags: ['Tradicional', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    imageUrl: '/src/assets/coffees/mocaccino.png',
    price: 9.9,
    tags: ['Tradicional', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    imageUrl: '/src/assets/coffees/chocolate-quente.png',
    price: 15.9,
    tags: ['Especial', 'Com Leite'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    imageUrl: '/src/assets/coffees/cubano.png',
    price: 19.8,
    tags: ['Especial', 'Alcoólico', 'Gelado'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    imageUrl: '/src/assets/coffees/havaiano.png',
    price: 12.6,
    tags: ['Especial'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    imageUrl: '/src/assets/coffees/arabe.png',
    price: 12.6,
    tags: ['Especial'],
  },
  {
    id: crypto.randomUUID(),
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    imageUrl: '/src/assets/coffees/irlandes.png',
    price: 19.8,
    tags: ['Especial', 'Alcoólico'],
  },
]
